name: CI for Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-20.04  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make tests.sh executable
        run: chmod +x tests.sh

      - name: Run tests
        run: ./tests.sh || exit 1
