name: CI for Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pandas numpy sqlite3 kagglehub

      - name: Make tests.sh executable
        run: chmod +x project/tests.sh

      - name: Run tests
        run: ./project/tests.sh || exit 1
